apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: edgegate
  namespace: default
spec:
  gatewayClassName: edgegate
  listeners:
    - name: http
      port: 80
      protocol: HTTP
    - name: https
      port: 443
      protocol: HTTPS
      hostname: "app.example.com"
      tls:
        mode: Terminate
        certificateRefs:
          - name: app-tls
