apiVersion: v1
kind: Service
metadata:
  name: edgegate
  labels:
    app.kubernetes.io/name: edgegate
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: edgegate
  ports:
    - port: 80
      targetPort: 80
